FROM pic-brm.eurafric.com:8082/nginx-eai-rootless:1.0

COPY ./dist/msiboa-cc-mf-followup-client /usr/share/nginx/html

RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]